sudo: required
language: python
python:
  - "3.6"
  - "3.7"
services:
  - docker
script:
  - python setup.py install
  - pytest -vs tests
  - bash docker_push.sh

before_install:
  - pip install pandas synapseclient
