sudo: required
language: python
python:
  - "3.6"
  - "3.7"
services:
  - docker
script:
  - python setup.py install
  - pytest -vs tests
  - echo "$synapse_pass" |  docker login --username "$synapse_user" --password-stdin docker.synapse.org
  - docker build . -t docker.synapse.org/syn18058986/challengeutils:$TRAVIS_BRANCH
  - docker push docker.synapse.org/syn18058986/challengeutils:$TRAVIS_BRANCH

before_install:
  - pip install pandas synapseclient
