sudo: required
language: python
services:
  - docker
script:
  - python setup.py install
  - pytest -vs tests
  - docker build .

before_install:
  - pip install pandas synapseclient

matrix:
  include:
    - os: linux
      python: 3.6
    - os: linux
      python: 3.7