sudo: required
language: python
script:
  - python setup.py install
  - pytest -vs tests

before_install:
  - pip install pandas synapseclient

matrix:
  include:
    - os: linux
      python: 3.6
    - os: linux
      python: 3.7