library("ggmap")
library(maptools)
library(maps)
library(synapseClient)
synapseLogin()
makeChallengeLocationMap() <- function(location_text_filePath, mapName) {
  challenge_stats = read.csv(location_text_filePath,sep="\t",stringsAsFactors = F)
  visited = challenge_stats$locations
  locations = c()
  for (loc in visited) {
    locations = c(locations, strsplit(loc,"[|]")[[1]])
  }
  locationDB = synTableQuery('select * from syn9730854')
  unique_locations = unique(locations)
  notFoundInDB = unique_locations[!unique_locations %in% locationDB@values$location]
  if (length(notFoundInDB)>0) {
    ll.visited = geocode(notFoundInDB)
    ll.visited$location = notFoundInDB
    ll.visited.all = rbind(locationDB@values,ll.visited)
    schema <- synGet('syn9730854')
    tableToAppend <- Table(schema, ll.visited)
    table <- synStore(tableToAppend)
  } else {
    ll.visited.all = locationDB@values
  }
  visited = data.frame(locations)
  mergedData = merge.data.frame(visited, ll.visited.all, by.x = "locations",by.y = "location")
  mergedData= mergedData[!is.na(mergedData$lat),]
  
  mergedData$combined <- paste(mergedData$lon, mergedData$lat)
  noduplicates <- mergedData[!duplicated(mergedData$combined),]
  count <- table(mergedData$combined)
  noduplicates$density <- count[match(noduplicates$combined, names(count))]
  visit.x <- noduplicates$lon
  visit.y <- noduplicates$lat
  pdf(mapName)
  map("world", fill=TRUE, col="grey", bg="white", ylim=c(-60, 90), mar=c(0,0,0,0))
  #log10 is 0 sometimes
  points(visit.x,visit.y, col="red", pch=20, bg=24, cex=log10(noduplicates$density)*2+1, lwd=.4)
  dev.off()
}
#Must make challenge_stats.tsv exist first (This file can be generated by running python createChallengeStatDf.py)
location_text_filePath <- "~/sage_projects/DREAM/DREAM-Utilities/statistics/challenge_stats.tsv"
makeChallengeLocationMap(location_text_filePath, "~/sage_projects/DREAM/DREAM-Utilities/statistics/all_challenge_locations.pdf")

location_text_filePath <- "~/sage_projects/DREAM/statistics/DM_challenge_locations.txt"
makeChallengeLocationMap(location_text_filePath, "~/sage_projects/DREAM/statistics/DM_challenge_locations.pdf")