library(data.table)
library(ggplot2)
library("ggmap")
library(maptools)
library(maps)
library(synapseClient)
synapseLogin()

### BEFORE RUNNING THESE FUNCTIONS MAKE SURE YOU RUN: python createChallengeStatDf.py
### TO GENERATE THIS FILE: challenge_stats.tsv


createChallengeParticipationPlot <- function(challengeStatDfPath, pdfPath) {
  challenge_stats = read.csv(challengeStatDfPath,sep="\t")
  Year = as.character(challenge_stats$createdOn)
  participants = data.frame(Year)
  numParticipants = c()
  for (users in challenge_stats$users) {
    numParticipants = c(numParticipants,length(strsplit(users, ",")[[1]]))
  }
  participants$Number = numParticipants
  participants$Name = challenge_stats$challenges
  participants = participants[order(participants$Year,participants$Number,decreasing = T),]
  participants$indexing = seq_along(participants$Year)
  
  ggplot(participants, aes(x=reorder(Name,-indexing),y=Number,fill=Year))+ geom_bar(stat="identity") + coord_flip() +
    ylab("Number of Participants") +
    theme(panel.background = element_blank(),
          axis.text.y = element_text(size=12),
          axis.title.y=element_blank(),
          axis.text.x  = element_text(size=12),
          title = element_text(size=14),
          legend.text=element_text(size=12),
          legend.justification=c(1,0), 
          legend.position=c(1,0))
  ggsave(pdfPath,width=17,height=10)
}
challengeStatDfPath="statistics/challenge_stats.tsv"
pdfPath = "statistics/challenge_participation.pdf"
createChallengeParticipationPlot(challengeStatDfPath,pdfPath)

### CREATE CHALLENGE LOCATION MAPS
makeChallengeLocationMap <- function(location_text_filePath, mapName) {
  challenge_stats = read.csv(location_text_filePath,sep="\t",stringsAsFactors = F)
  visited = challenge_stats$locations
  locations = c()
  for (loc in visited) {
    locations = c(locations, strsplit(loc,"[|]")[[1]])
  }
  locationDB = synTableQuery('select * from syn9730854')
  unique_locations = unique(locations)
  notFoundInDB = unique_locations[!unique_locations %in% locationDB@values$location]
  if (length(notFoundInDB)>0) {
    ll.visited = geocode(notFoundInDB)
    ll.visited$location = notFoundInDB
    ll.visited.all = rbind(locationDB@values,ll.visited)
    schema <- synGet('syn9730854')
    tableToAppend <- Table(schema, ll.visited)
    table <- synStore(tableToAppend)
  } else {
    ll.visited.all = locationDB@values
  }
  visited = data.frame(locations)
  mergedData = merge.data.frame(visited, ll.visited.all, by.x = "locations",by.y = "location")
  mergedData= mergedData[!is.na(mergedData$lat),]
  
  mergedData$combined <- paste(mergedData$lon, mergedData$lat)
  noduplicates <- mergedData[!duplicated(mergedData$combined),]
  count <- table(mergedData$combined)
  noduplicates$density <- count[match(noduplicates$combined, names(count))]
  visit.x <- noduplicates$lon
  visit.y <- noduplicates$lat
  pdf(mapName)
  map("world", fill=TRUE, col="grey", bg="white", ylim=c(-60, 90), mar=c(0,0,0,0))
  #log10 is 0 sometimes
  points(visit.x,visit.y, col="red", pch=20, bg=24, cex=log10(noduplicates$density)*2+1, lwd=.4)
  dev.off()
}
#Must make challenge_stats.tsv exist first (This file can be generated by running python createChallengeStatDf.py)
location_text_filePath <- "statistics/challenge_stats.tsv"
makeChallengeLocationMap(location_text_filePath, "statistics/challenge_locations.pdf")

#location_text_filePath <- "~/sage_projects/DREAM/statistics/DM_challenge_locations.txt"
#makeChallengeLocationMap(location_text_filePath, "~/sage_projects/DREAM/statistics/DM_challenge_locations.pdf")
